### ISSUE TITLE
Resources.zip is not necessary in the compiled version, it can be downloaded manually. Also gitkeep is not necessary too

### ISSUE THREAD

**Issue by cloudcloudskies** [Fonta22/GDTextureRestorer#14]

**Comment by Fonta22** [comment]
I think it's more practical to have the `Resources.zip` file inside the main zip, since you don't need to waste time on installing it manually, even it makes it weigh more. In the other hand, I agree with what you point about the `.gitkeep` file, it was only for the repo and I forgot and included it by error. I'll fix that, thanks! 👍🏻
